### ISSUE TITLE
 Fullscreen button should be optional

### ISSUE THREAD

**Issue by bjonnh** [Triply-Dev/YASGUI.YASQE-deprecated#139]
I am integrating YASQE in a JavaFX (TornadoFX/Kotlin) webview. I'm calling:
yasqe.setOption("fullScreen", true);   

to be directly in full -screen (undocumented).

I also added a css to remove the button (as there do not seem to be an option for that).

See: https://www.bjonnh.net/share/matcher.png  to have an idea of how that look now.

**Comment by LaurensRietveld** [comment]
I'm not fond of programatically disabling UI element that can be disabled with css otherwise. It just creates overhead, as why wouldnt we create a flag to hide the query button or share button. In yasgui there are even more input element you might want to hide (e.g. the endpoint selector, the hamburger icon, etc).

**Comment by bjonnh** [comment]
That's a way to see it too. Is there a way to disable the Escape key so it stop exiting full screen ?

**Comment by LaurensRietveld** [comment]
This is not an issue anymore in the latest version (we removed the fullscreen functionality).
