### ISSUE TITLE
Suggestion for variable insertion via VALUES (poor man's sparql templating ...)

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASQE-deprecated#24]
Thinking about what we discussed yesterday, and taking into account that general templating for sparql queries may be tricky, I wonder if the VALUES statement could be exploited for this.

VALUES could be used by the author of a query to define defaults values for queries, which are meant to be overridden by users of this query, for example:

```
...
FILTER ( lang(?label) = ?language )
...
VALUES ?language { "en" }
```

Perhaps, YASGE could support this, in offering a "Edit values" function, where for each VALUES parameter an editable field with the value is displayed, and the result is inserted into the query.

The more general case of the VALUES statement looks like this (http://www.w3.org/TR/sparql11-query/#inline-data):

```
VALUES (?x ?y) {
  (:uri1 1)
  (:uri2 UNDEF)
}
```

so parsing would a bit more difficult, and values would have to be given in a grid of editable fields.

The advantage of such an approach would be that the author of a query can designate "tweak here" spots. Other variables, which should be bound during the execution of the query, would not be exposed. Thus, the inner working is not disturbed, and the default values - hopefully in combination with the variable names - can provide hints for the users on what to fill in.

Of course, all of this can be achieved by custom coding - but it would make a nice and rather general feature too, wouldn't it?

**Comment by LaurensRietveld** [comment]
Not completely sure, but this replace functionality sounds quite a bit like http://spinrdf.org/spin.html#spin-templates.
I like the idea though, but I'm still hesitant whether there is a 'catch' somewhere. 
I suggest we try this first as a gist, see how it goes, and possibly add it later on to the library. I'll let you know when I've finished it

**Comment by jneubert** [comment]
It would be great to be able to trigger a VALUES parameter replacement via some URL argument.

**Comment by jneubert** [comment]
I applied a similar logic within a [perl script](https://github.com/jneubert/skos-history/blob/master/bin/create_change_statistics.pl), which calls queries with varying parameters. For perl, I couldn't find a libarary which parses a query and gives me the VALUES clause in an accessible fashion, so I simply based the query parsing on a regex plus whitespace convention (minimal: `values ( ... ) { ( ... ) }`). 
This works fine for me. I didn't try however to do replacements with multiple sets of VALUES (which are allowed by the spec).
My [question on pub-sparql-dev mailing list](http://lists.w3.org/Archives/Public/public-sparql-dev/2014OctDec/0022.html) didn't reveal unknown traps or caveats so far.

**Comment by LaurensRietveld** [comment]
I've been checking how other tools do this. Jena, for instance, approaches it by replacing the variables in the query:
http://jena.apache.org/documentation/query/parameterized-sparql-strings.html 
Essentially they are simply applying a regex (p = Pattern.compile("([?$]" + var + ")([^\w]|$)");) and inserting the value.

So Jena is not even using placeholders, but simply replacing the regular sparql variable. I'm not sure on the best way to approach this. 
The Jena approach seems fragily, but straight forward. One problem it solves (contrary to the values clause) is scoping w.r.t. different clauses, such as subqueries, or service queries. (not sure how the VALUES clause would behave for those cases)

Is there a reason why you'd prefer the values over replacing the variables themselves?

**Comment by jneubert** [comment]
Yep, indeed there are three reasons:

1) a VALUES clause hints at which variables are meant to be replaced, and can provide a kind of a "config section" for the query
2) it provides reasonable defaults (which may also serve as example values) and puts the query in a executable state
3) a generic interface could offer exactly these variables for editing (which had to be defined out of band otherwise, because you wouldn't rather let an non-technical user mess with every variable in a query)

If a query has multiple VALUES clauses in different scopes, I suppose it get's much more difficult. I'm not sure if it is worth the effort trying to deal with this - presumably relatively rare - case.

**Comment by LaurensRietveld** [comment]
But doesnt the jena solution supports 2 (well, at least the executable state) and 3 as well?
And the jena solution would solve the scoping issue.
Plus: the jena solution would work on -any- query, where this solution only works on queries with a values clause right? (or do you prefer a hybrid apprach?)
As you see, I'm still quite hesitant ;)

**Comment by jneubert** [comment]
Hmm - I don't see how Jena does this, perhaps I'm missing the spot.

Considering the query with an parameter as a values clause:

```
PREFIX  skos:   <http://www.w3.org/2004/02/skos/core#>
SELECT  *
WHERE
{
  VALUES (?language) {
    ( "en" ) 
  }
  ?concept skos:preflabel ?pref ;
    skos:altLabel ?alt .
  FILTER (lang(?pref) = ?language)
  FILTER (lang(?alt) = ?language)
}
```

I presume that according to [this](http://jena.apache.org/documentation/query/parameterized-sparql-strings.html#variable-parameters) in Jena the query would be:

```
PREFIX  skos:   <http://www.w3.org/2004/02/skos/core#>
SELECT  *
WHERE
{
  ?concept skos:preflabel ?pref ;
    skos:altLabel ?alt .
  FILTER (lang(?pref) = ?language)
  FILTER (lang(?alt) = ?language)
}
```

Out of band, you'd have to know that you _have to_ replace `?language` with a two-character language code to get any result at all. And the application (or the user ...) has to know that it shouldn't touch `?pref` or `?alt`.
But perhaps I have missed the point completely ...

**Comment by LaurensRietveld** [comment]
Your right in that using default values won't work for this approach. However, that is how parameterized queries work in general, I believe.
This is the case for SQL, but also for virtuoso (uses '??' or '$?' to specify a parameter), and sesame and jena.

I'm not sure on the motivation behind this approach: whether this is because of legacy issues (SPARQL 1.0 does not have the VALUES clause), or whether there is another reason.
I'm sensitive to the legacy argument as well though. There is still a surprising amount of 1.0 endpoints out there... (http://sparqles.okfn.org/interoperability)

**Comment by jneubert** [comment]
Hmm - I think the use case for parametrized queries in general is slightly different: In SQL they address solely developers who embed these queries in their own code. YASQE is about building an interface for the "end user" of the query (in an editing environment for only the query itself, without enclosing code for setting the parameters).
The mechanisms used in the libraries you cite pre-date SPARQL 1.1 (in my older scripts for sparql-based web services I use a similar approach - it was just the only available way). The use of VALUES for that seems to be not very wide spread - however, Eric Prud'hommeaux mentioned using it for the injection of user data, and the d3sparql.js guys inject the ever-changing starting point of the drill-downs in their tree visualization via VALUES.
That said - your concerns about legacy endpoints are valid. Offering query parameters only for those people who write queries requiring SPARQL-1.1 is not very nice. On the other side, a hybrid approach would not only require more work, but also introduce a unpleasant legacy. Tough nut ...

**Comment by osma** [comment]
There's a related discussion about parametrized / pre-bound queries currently active at the Jena developers mailing list, starting with [this message](http://mail-archives.apache.org/mod_mbox/jena-dev/201506.mbox/%3C557F95E6.9070205%40knublauch.com%3E).

In particular, the (currently) [last message](http://mail-archives.apache.org/mod_mbox/jena-dev/201506.mbox/%3C5580AEE2.3030503@knublauch.com%3E) in the thread, by Holger Knublauch, has an example of how SHACL templates could be used to express that a SPARQL query can take arguments (with some metadata) and those then become pre-bound variables in the executed query, similar to inserting a VALUES clause.

I'm not really sure how to apply all this in YASQE, but maybe reading that thread could help revive this discussion.

**Comment by lisp** [comment]
given the resources which a processor devotes to query planning, there can be a significant performance advantage to a mechanism which operates on the abstract, internal query over one which treats each request as a malleable text document to be arbitrarily modified.
given this, as both the sparql language and the request have sufficient capacity to identify and to communicate the values information, it is better to handle the values as a request argument and integrate them structurally.
see https://github.com/dydra/http-api-tests/tree/master/extensions/sparql-protocol/values

**Comment by LaurensRietveld** [comment]
Thanks @osma  for the link. 
@lisp @jneubert  Before I start implementing this, I'm curious: what are the different use-cases you'd like to support? Do these use cases only involve setting parameters via a URL, or is a UI interface desired as well?

**Comment by artob** [comment]
Pinging @jaw111 as well, since he originally defined the business requirements that formed the basis for the @dydra implementation of this capability.

**Comment by lisp** [comment]
the particular uses cases which have been presented to us involve augmenting a saved/stored query with values which would be supplied as post content more likely that as url query arguments.
while the latter is also possible and will be supported on our end, but we expect the post variation to be more likely.
we are pursuing an implementation in which the prototype query will contain the site for the values to be introduced, which means an editor need not do anything special as the edited query can contain "prototypical" values, to be supplanted in production.

**Comment by jaw111** [comment]
Simplified use case is where we want to get/set the labels for a set of resources. Simple query templates (without VALUES) might be:

get labels

```
select $uri ?label
where {
  $uri rdfs:label ?label
}
```

set labels

```
delete {
  $uri rdfs:label ?old_label
}
insert {
  $uri rdfs:label $new_label
}
where {
  $uri rdfs:label ?old_label
}
```

Here I use the convention to use $ prefix to indicate (to a human reading the query) the variables for which an initial binding is intended to be injected during execution of the query.

The use case we have is that we want to get/set the labels for multiple resources in one HTTP request.

**Comment by osma** [comment]
I sense some potential confusion in this discussion as people arrive with various background expectations...

I understand that @lisp, @bendiken and @jaw111 are talking about how to pass extra parameters to a SPARQL endpoint (Dydra in this case) alongside the actual query, to be incorporated into the query by the request processor, which is apparently more efficient than performing string manipulation on the query text.

@jneubert on the other hand wants specific functionality in the YASQE tool: to be able to pass URL parameters to the web page where YASQE is embedded, so that YASQE can plug these parameters into the SPARQL query before it is sent to the endpoint in another HTTP request. This could be implemented in several ways, e.g. YASQE could perform intelligent string substitution on the query (using JavaScript that it is implemented in), for example by adding/modifying a VALUES clause. Or conceivably, if the endpoint supported something like what Dydra does, those parameters could be added as extra URL/POST parameters in the subsequent request to the endpoint - but since that is not standardized at the moment even in SPARQL 1.1, I wouldn't expect YASQE to rely on that any time soon.

The important distinction here is which HTTP request we are talking about. As I understand it, this issue is mainly about the request for the web page where YASQE is embedded, not the subsequent HTTP request to the SPARQL endpoint, though it will also be affected indirectly by the parameter substitution.

**Comment by jneubert** [comment]
Thanks, @osma, for the clarification. My suggestion indeed aimed for low hanging fruits by modifying the query string in a preprocessing step (executed in Javascript/YASQE).

In my eyes, a VALUES clause is a nice starting point, because

1) it makes use of a standard SPARQL 1.1. mechanism, which is already widespread and which is relatively easy to understand ( (so it does not depend on further standardization and its implementation), 
2) it exposes the possible "tweaking points" within the query itself,
3) defaults can be provided in a straight-forward way, and the query is executable using the given defaults

Downside is that string manipulation can go wrong (e.g., by omitting required quotation marks), resulting in an invalid query. But this happens in the same way when people try to modify a query directly, without substitution mechanisms.

**Comment by jneubert** [comment]
My main use case is providing queries for certain datasets, which can and should be modified by users, in YASQUE as an IDE-like environment.

See for example https://github.com/jneubert/skos-history/tree/master/sparql/stw/README.md. An example query is

http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/added_concepts_by_category.rq

By a very simplistic wrapping script, some VALUES pararmeters are recognized and can be replaced, e.g.

http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/added_concepts_by_category.rq&language=de

The context for such queries mostly is exploration.

Yet, I've used it in production-near (beta) environments,too, where parametrized links to queries are provided. In this setting, only the result of the query execution is shown to the users via YASR. For an example of these, see

http://zbw.eu/stw/versions/8.14/version_changes/about.en.html

**Comment by osma** [comment]
(sorry for duplication, I started writing these before @jneubert's explanation, I think another take is still useful so I'm not deleting my own text even if it's similar to the above)

> Before I start implementing this, I'm curious: what are the different use-cases you'd like to support? Do these use cases only involve setting parameters via a URL, or is a UI interface desired as well?

As I understand @jneubert's use case, it is currently about setting parameters via URL. For example this one (wrapped for readability):

```
http://zbw.eu/beta/sparql-lab/
?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/added_concepts.rq
&oldVersion=8.10&newVersion=8.12&language=de
```

Here `oldVersion`, `newVersion` and `language` are (optional) parameters that should be plugged into the VALUES clause in the SPARQL query instead of the default values (undef, undef and "de", respectively). At the moment this is implemented in [another script](http://zbw.eu/beta/sparql-lab/sparql-lab.js) using regular expressions, but it would be neat if YASQE could do this on its own.

What I'd suggest is that, instead of YASQE directly looking at URL parameters, it could provide an API for accessing and modifying VALUES clause(s) in the query. So something like

``` js
// read the default values
var values = yasqe.getValuesClause();

// set the parameters within a VALUES clause
yasqe.setValuesClause('oldVersion', '8.10');
yasqe.setValuesClause('newVersion', '8.12');
yasqe.setValuesClause('language', 'de');
```

Setting the parameters would involve determining their type, i.e. literal or resource, so that they could be serialized properly in the query. This could be done by parsing the default values given in the original VALUES clause. `undef` default values (as used in the above example) are problematic since no type can be inferred from them, but maybe the default could then be to use literals unless the given value starts with `http[s]://` - and the `setValuesClause` method could take a type argument for setting it explicitly.

If YASQE supported an API like this, then it would be trivial for the embedding page to look at the URL parameters and call the YASQE methods accordingly. Or alternatively, make a UI of some sort for choosing those parameters.

**Comment by jneubert** [comment]
To provide an UI for the query substitution sounded like a good idea when I made the suggestion. However, as of today I'm not so sure how useful this would be in practice. The only mechanisms to provide some guidance for the users are the variable name and optionally a default value. In very simple cases, that may be enough (e.g. ?language "en" lets you suppose that you could insert other two character language codes). But more often than not additional explanations or even an exploration of the dataset (which languages are present?) may be requiered. The best place for such explanations could be comments near a VALUES clause.

**Comment by lisp** [comment]
if the pertinent use case reduces to single-value substitution rather than integrating a solutions field, shouldn't something like sesame's support for sparql request parameters in combination with individual BIND clauses suffice?
in this case the client / ide need not modify the query as the bindings are added to the request uri.
if one wanted to articulate an interface, clauses like

```
BIND (?variableFromAPI AS ?variable)
```

would serve the purpose and support an ide which wanted to provide ui support for bindings.
a VALUES clause would require a more complex implementation, as it does not permit variables in the DataBlock

**Comment by jneubert** [comment]
Well, it's not necessarily single-value: In [this example](http://zbw.eu/beta/sparql-lab/?endpoint=http://zbw.eu/beta/sparql/stw/query&queryRef=https://api.github.com/repos/jneubert/sparql-queries/contents/stw/categories_by_descriptors.rq), multiple URIs are injected. A single-value BIND would require multiple requests + custom script processing in such a case.

**Comment by jneubert** [comment]
I suppose @osma's suggested `yasqe.setValuesClause()` function could accept arrays as well as single values.

The wrapping script, which would invoke such a function, could implement a parser for URLs like:

```
...&setValues=(oldVersion=8.10;newVersion=8.12,language=de;uri=http://x,http://y,http://z)
```

or alternatively try to interpret every parameter, which is not known otherwise (such as query=), as input for setValuesClause().

**Comment by osma** [comment]
[Here](https://gist.github.com/osma/4e1098391f0d54806e29) is a very rough first implementation of a generic VALUES templating mechanism using nothing but regular expressions. I'm sure there are bugs and unhandled special cases (for example, embedded quotes in literals). It also only works with a single value row, not multiple ones as requested by @jneubert.

The idea is that you call `replaceQueryValues` with the original SPARQL query and an associative array (object) of new values to plug into the query in place of the original (default) values, and it returns the modified query. See the `modifyQueryValues` function for an example that takes the value from a UI component (dropdown list), splices that into the current query in YASQE and re-executes the query.

But the original request was to have a mechanism like this in YASQE itself, not in external code such as this.

**Comment by LaurensRietveld** [comment]
Thanks for the input everyone. 

I'll try to extend the YASQE api with a 'setValuesClause' and 'getValuesClause'. Afterwards, if there is a need, I might add a GUI interface for this in YASGUI.

Implementation will actually be similar to @osma (thanks for that btw): the grammar in YASQE functions as a tokenizer, i.e. dissecting a query and easily extracting values clauses from them is not trivial. So it won't be possible to avoid regular expressions altogether

ps. I'm slow with the responses atm: working on dissertation

**Comment by lisp** [comment]
did you consider linking up with verborgh's sparql parsing effort: https://github.com/RubenVerborgh/SPARQL.js ?

**Comment by LaurensRietveld** [comment]
I understood they were busy combining their parser with YASQE, particularly to use it on the LDF interface.
It is not trivial to combine both though, considering YASQE has to parse a query incrementally, and has to deal with invalid (e.g. incomplete) queries.

**Comment by lisp** [comment]
if one is in a position to generate the parser straight from a bnf, that specification would be complicated, as you would have to name everything which you want to recognize, but then the parser could opportunistically just try the productions.

**Comment by osma** [comment]
@LaurensRietveld Here's a newer version of my VALUES substitution code, if you want to use it:
https://github.com/NatLibFi/Finto-data/blob/master/tools/ysa-to-yso/ysa-to-yso.js#L45

You can see it in action here: http://ysa-to-yso.dev.finto.fi/
(UI is Finnish though..)

**Comment by jneubert** [comment]
Integrated Osmas code in https://github.com/jneubert/sparql-gui-gh/blob/master/sparql-lab.js - works very well for me. Thank you so much!

**Comment by LaurensRietveld** [comment]
Thanks for the good discussion. This is still an open feature for yasgui, so I propose to continue the discussion in the new Yasgui monorepo: https://github.com/TriplyDB/Yasgui/issues/137
